---
name: Config-Extend-MySQL
version: 0.04
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: Extend your favourite .INI parser module to read MySQL configuration file
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Config::Tiny: 0
  File::Basename: 0
  File::Read: 0
  File::Spec::Functions: 0
  UNIVERSAL::require: 0
  perl: 5.006
build_requires:
  Test::More: 0
provides:
  Config::Extend::MySQL:
    file: lib/Config/Extend/MySQL.pm
    version: 0.04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
