--- #YAML:1.0
name:                Config-Extend-MySQL
version:             0.01
abstract:            Read MySQL configuration file
license:             ~
author:              
    - Sebastien Aperghis-Tramoni <sebastien@aperghis.net>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Config::Tiny:                  0
    File::Basename:                0
    File::Read:                    0
    File::Spec::Functions:         0
    Test::More:                    0
    UNIVERSAL::require:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
